# Generated by Django 3.1.4 on 2021-01-04 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
