# Generated by Django 3.1.4 on 2021-01-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_auto_20210104_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio',
            new_name='fecha',
        ),
    ]
